name: kali-linux and metasploitable2
services:
    metasploitable2:
        container_name: metasploitable2
        stdin_open: true
        tty: true
        image: tleemcjr/metasploitable2:latest
        command: sh -c "/bin/services.sh && bash"
---
services:
  kali-linux:
    image: lscr.io/linuxserver/kali-linux:latest
    container_name: kali-linux
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - "TITLE=Kali Linux" #optional
    volumes:
      - ./config:/config
      - ./var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
      - 3001:3001
    #devices:
      #- ./dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
